# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('Chair', 'Chair'), ('ViceChair', 'ViceChair')], max_length=20)),
                ('previous_mun_exp', models.TextField()),
                ('previous_org_com_exp', models.TextField(blank=True, null=True)),
                ('previous_exe_board_exp', models.TextField()),
                ('other_exp', models.TextField(blank=True, null=True)),
                ('slide_position', models.TextField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('file', models.FileField(upload_to='useruploads/')),
                ('ques1', models.TextField(blank=True, null=True)),
                ('ques2', models.TextField(blank=True, null=True)),
                ('ques3', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('institute', models.CharField(max_length=120)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('dob', models.DateField(auto_now_add=True)),
                ('city', models.CharField(max_length=120)),
                ('updatedtime', models.DateTimeField(auto_now=True)),
                ('settime', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
