# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiveboard',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='useruploads/'),
        ),
        migrations.AlterField(
            model_name='executiveboard',
            name='slide_position',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
